import { ChakraProvider } from "@chakra-ui/react"

export const metadata = {
  title: 'Your Blog',
  description: 'Generated by Next.js',
}

export default function RootLayout({ children }) {
 return (
    <html lang="en">
      <body>
        <ChakraProvider>{children}</ChakraProvider>
        </body>
    </html>
  )
}
